import type { NextPage } from 'next';
import Head from 'next/head';
// import styles from '../styles/Home.module.css';
import PokemonList from '@components/PokemonList';
import useGetPokemon from 'hooks/useGetPokemon';

const Home: NextPage = () => {
	const data = useGetPokemon();

	return (
		<div className='container mx-auto'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='container mx-auto'>
				<PokemonList pokemon={data} />
			</div>
		</div>
	);
};

export default Home;
